version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3307:3306"
    networks:
      - mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

  account-management-service:
    image: shivammittal242/account-management-service:tag
    container_name: account-management-service-container
    ports:
      - "8091:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mysql-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
